#! /bin/bash

bspc monitor DP-1 -d web dev term file 5 6 7 8
bspc monitor eDP-1 -d 9 0

bspc config top_padding          0
bspc config bottom_padding       0
bspc config -m DP-1 bottom_padding  27

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
