#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config top_padding           0
bspc config bottom_padding        0
bspc config top_padding           24

bspc config normal_border_color   "#282828"
bspc config focused_border_color  "#D79921"

bspc config border_width          2
bspc config window_gap            0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
